obj-$(CONFIG_SIKLU) += siklu_device_config.o common_boot.o common_config.o bank_management.o siklu_load_device_configurations.o siklu_nand_boot.o siklu_nfs_boot.o common_fdt.o common_mtd.o siklu_spoe_command.o siklu_load_device_configurations.o common_gpio.o siklu_shw.o siklu_board_hw_revision.o siklu_n366_board_hw_revision.o
obj-$(CONFIG_SIKLU_ENV_IS_IN_MTD_NOR) += mtd_nor_env.o
