obj-$(CONFIG_SIKLU) += siklu_device_config.o common_boot.o common_config.o bank_management.o siklu_load_device_configurations.o siklu_nand_boot.o siklu_nfs_boot.o common_fdt.o common_mtd.o siklu_spoe_command.o
obj-$(CONFIG_SIKLU_ENV_IS_IN_MTD_NOR) += mtd_nor_env.o

obj-$(CONFIG_SIKLU) += board/
