# (C) Copyright 2016 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := mx6ullevk.o \
	 mx6ullevk_siklu_pcb19x.o mx6ullevk_siklu_api.o \
	 mx6ullevk_siklu_mutual_env.o

obj-$(CONFIG_SIKLU_BOARD) += mx6ullevk_siklu_pcb19x_spi.o	\
	mx6ullevk_siklu_hw.o 