/*
 * siklu_def.h
 *
 *  Created on: Aug 29, 2017
 *      Author: edwardk
 */

#ifndef SIKLU_DEF_H_
#define SIKLU_DEF_H_



#define SIKLU_BIST_ENVIRONMENT_NAME "bist"
#define SIKLU_BIST_MUT_ENVIRONMENT_NAME "SK_bist" // siklu_remark002



#define CONFIG_CPLD_DEFAULT_BUS		1
#define CONFIG_CPLD_DEFAULT_CS		1
#define CONFIG_CPLD_DEFAULT_SPEED	10000000
#define CONFIG_CPLD_DEFAULT_MODE	SPI_MODE_0
#define CONFIG_CPLD_DIP_MODE_REG_ADDR 0x8

#define CONFIG_RFIC_DEFAULT_BUS			0
#define CONFIG_RFIC70_DEFAULT_CS		0
#define CONFIG_RFIC80_DEFAULT_CS		1
#define CONFIG_RFIC_DEFAULT_SPEED	1000000
#define CONFIG_RFIC_DEFAULT_MODE	SPI_MODE_0


#define SIKLU_SYSEEPROM_SF_OFFS		0x1f0000
#define SIKLU_SYSEEPROM_SF_SIZE		0x010000 // defined also in drivers/mtd/spi/sf.c

#endif /* SIKLU_DEF_H_ */
